### ISSUE TITLE
Trap on error

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#1]
Description: when the script exits prematurely, one last attempt to notify slack should be made.

- Read the bash manual for the `trap` builtin https://www.gnu.org/software/bash/manual/bash.html
- Figure out what invocation of trap will catch the case where one of the commands result in a premature abort (due to `set -e`)
- Implement

**Comment by darrenge** [comment]
Is there anything specific that you would want or not want in the slack notification when an error / exit occurs?

**Comment by msprotz** [comment]
I think just sending something like "The ci script exited abnormally; error codes: `${PIPESTATUS[@]}`" would be totally sufficient. This an exceptional condition, which means that one of us would have to look at the VSTS logs anyhow.

**Comment by darrenge** [comment]
How about who slack message goes to? Do the same logic as logging that checks channel if c_ or a direct message is slackid_?

The problem with that logic is that we might not have that info when the script crashes.

**Comment by msprotz** [comment]
No logic in a trap handler -- just a simple one-liner should suffice. We just need a infaillible notification to go out. The notification should go somewhere, I suggest #everest-build

**Comment by darrenge** [comment]
Oh good ... this got easier. :)

**Comment by msprotz** [comment]
Fixed by @darrenge in fab785a
