### ISSUE TITLE
put the extraction and test of chacha / wasm in HACL* under CI

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#102]
```
jonathan@chartreuse:~/Code/hacl-star/code/salsa-family (master) $ /Users/jonathan/Code/kremlin/krml   -ccopt -march=native -verbose -ldopt -flto -I /Users/jonathan/Code/hacl-star/code/lib/kremlin -I /Users/jonathan/Code/kremlin/kremlib -I /Users/jonathan/Code/hacl-star/specs -I . -drop Prims,Hacl.UInt8,Hacl.UInt16,Hacl.UInt32,Hacl.UInt64,Hacl.UInt128,Hacl.Endianness,Hacl.Cast,Hacl.Spec.*,Spec.*,Seq.* -add-include '"testlib.h"' /Users/jonathan/Code/kremlin/kremlib/testlib.c -tmpdir chacha-c -bundle 'Chacha20=Hacl.Impl.*,Chacha20,Hacl.Lib.*' chacha-c/out.krml -wasm -no-prefix Hacl.Test.Chacha20 -d wasm,wasm-calls
```

then:

```
jonathan@chartreuse:~/Code/hacl-star/code/salsa-family/chacha-c (master) $ \cp ~/Code/kremlin/kremlib/js/*.js . && d8 --allow-natives-syntax main.js
```

This means that the CI machine and/or CI docker containers will need a recent d8.

**Comment by msprotz** [comment]
with https://github.com/FStarLang/kremlin/commit/1e6b8f05984859797beb35b4de6bbb7e7967b0f7 you no longer need to manually copy the files, kremlin will do it for you; also, it'll generate a README in the output directory

**Comment by beurdouche** [comment]
@tahina-pro what is the status of WASM on the build machine ?

**Comment by msprotz** [comment]
I made wasm tests compatible with the latest version of node so now the setup should be simpler, and we should be able to get rid of d8 in favor of the latest version of node

**Comment by s-zanella** [comment]
We use node now for CI and we run WASM tests as part of KreMLin CI.
