### ISSUE TITLE
upgrade the wasm package in OPAM

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#108]
Benjamin perhaps you'd be interested:

From Andreas Rossberg:

>new Wasm release tag is here:
>
>https://github.com/WebAssembly/spec/releases/tag/v1.0

I'm happy to fix the kremlin breakage if needed

**Comment by msprotz** [comment]
This is a prerequisite for #102

**Comment by msprotz** [comment]
@beurdouche did you eventually submit a pull request to Andreas?

**Comment by beurdouche** [comment]
Yes, it was merged today, I think he did update the release too...
I'll do the PR for the opam package tomorrow.

**Comment by msprotz** [comment]
Wonderful, thanks!
