### ISSUE TITLE
Lack of sharing for the ulong target

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#11]
The F* Makefile needs to be fixed so that we don't verify the crypto twice...

**Comment by darrenge** [comment]
Who should we assign this to?

**Comment by sishtiaq** [comment]
Surely the crypto's been moved out of F* now?

**Comment by msprotz** [comment]
As far as I know, it hasn't -- we're still running it as part of our CI.

This is one thing that I hope will be fixed as a byproduct of the switch to SCons for F*. So, I don't have anyone in particular to assign it to, except perhaps Barry, who volunteered to make the initial effort for the SCons switch.

**Comment by BarryBo** [comment]
Yes, this should get better with the changeover to Scons.  I will keep the issue alive until I am confident of this.

**Comment by msprotz** [comment]
Right now, `ulong = uall + low-level's extra target`. As soon as low-level is remove from the F\* tree in favor of HACL\*, then this issue will resolve by itself.
