### ISSUE TITLE
improved kremlin CI

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#110]
- [ ] it'd be great to have a d8 binary to download as part of travis to check that the wasm target in kremlin is not broken

if @tahina-pro build a d8 binary in the docker images, can we put a tarball somewhere that I can download, with a statically-linked d8 binary for ubuntu 16.04? happy to change .ci/script.sh afterwards

- [ ] get the everest script to check & download the right z3 so that we can put verification of Server.fst under CI

**Comment by s-zanella** [comment]
Outdated. KreMLin is now under CI on Azure DevOps.
