### ISSUE TITLE
the badges are useless

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#12]
seems like the badges in README.md are not very meaningful and pick the latest build, not the master branch... any way we can fix that?

**Comment by darrenge** [comment]
Yes - these badges pick up the latest build on any branch. I don't think we need to have the badges on this page and have a dashboard. The dashboard will show these badges, so once that is in place, this won't be an issue.

**Comment by msprotz** [comment]
Agreed

**Comment by darrenge** [comment]
No need to track this here ... so closing
