### ISSUE TITLE
offer an option to regenerate the hints for non-master branches

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#13]
the script enforces that the branch is master but we may want to be more generic than that

**Comment by darrenge** [comment]
Is this valid any more? Looking at refresh_hints() in ci, it has "$CI_BRANCH" through out

**Comment by msprotz** [comment]
Yes, I eventually added that... this has to be triggered through VSTS's UI but theoretically it should work. I think it's just untested. Do you want to try it out on `c_relational-ci_r3`?

**Comment by msprotz** [comment]
For F*, that is

**Comment by darrenge** [comment]
Fired off FStar-Nightly-Linux build ...

**Comment by msprotz** [comment]
That worked. Thanks for the test! Closing.
