### ISSUE TITLE
Links to CI and dashboard in README.md appear to be dead?

### ISSUE THREAD

**Issue by achamayou** [project-everest/everest-ci#130]
The README file references:

https://msresearch-ext.visualstudio.com/Everest

That gives me a 404 page.

and

http://everestdashboard.azurewebsites.net/

Which doesn't seem to resolve at all.

The reason I am looking for the CI is that I would to like to try and contribute an improvement to tag the latest successful docker image (for example "success" or a similar term), to make it easier for me to refresh the extracted code I need in my project.

**Comment by achamayou** [comment]
@wintersteiger suggests the correct link should be https://msr-project-everest.visualstudio.com/Everest, which gives a more expected 401 Not authorized.

**Comment by msprotz** [comment]
Thanks for refreshing the code! Please let me know if there's anything I can improve on the packaging / distribution. I've added you to the right team that should allow you to see those CI results.

**Comment by s-zanella** [comment]
Fixed by 297d98f04cb3c863fba21079ffe4f8125798882b
