### ISSUE TITLE
VSTS doesn't allow one to see more than 10 builds in the past

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#14]
We should have a file somewhere in the ci-logs repository that is append only where we record what got build and when.

**Comment by vkanne-msft** [comment]
Can we see if we can configure vsts to show more builds?alternatively our Middleware is keeping record of all builds.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by msprotz** [comment]
I spend a solid 10 minutes trying to understand where to configure that and gave up. Happy to get some help!

**Comment by vkanne-msft** [comment]
I am thinking this should keep it

[cid:image001.png@01D25133.0933B010]

**Comment by msprotz** [comment]
Images as email attachments don't generate an embedded image on github issues

**Comment by vkanne-msft** [comment]
seems pasting images also don't work. Check the link.

**Comment by vkanne-msft** [comment]
This can be viewed today on VSTS under build definition -> HIstory
