### ISSUE TITLE
figure out how to get the branch we're building from VSTS

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#15]
Right now there's a lot of git wizardry involved to recover an approximate notion of the branch we're building from the state of the repository that VSTS set us in. There ought to be a way to get that information passed to the script...!

**Comment by vkanne-msft** [comment]
https://www.visualstudio.com/en-us/docs/build/define/variables

**Comment by msprotz** [comment]
Fixed by 7635ddc
