### ISSUE TITLE
Implement hint regeneration for mitls

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#18]

**Comment by darrenge** [comment]
This is the same process as the hints regeneration for FStar, right?
It looks like we could just use something similar to "refresh_fstar_hints" that is in ci already.  Just call it refresh_mitls_hints () and change the check at the beginning and the push at the end.

One thing to note - hint regeneration for FStar happens on the nightly build run. There isn't a nightly build run for milts so it would just go in "mitls-ci"?

**Comment by msprotz** [comment]
I'd say this needs to be done on (a new) mitls-nightly, essentially because there may be too many conflicts if there's a lot of hint regeneraiton commits.

However, miTLS CI is currently broken -- we need to give up on building mitls.exe and client.out in the miTLS-specific CI. Once we fix that, we'll have a reference "green" CI run for miTLS, and then we can do the same thing in a new mitls-nightly action + regenerate hints.

**Comment by msprotz** [comment]
I removed the "build mitls.exe" part of mitls-ci, and Antoine is working on restoring verification
