### ISSUE TITLE
Figure out how to intermingle stdout and stderr properly

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#19]
Basically, we want stderr isolated to take a quick peek at the build log, but for full investigations, we need to look at a proper intermingling of stdout and stderr. Right now, we only have stdout (alone) and stderr (alone). We want stderr (alone) and stdout+stderr (interleaved properly together).

This is tricky, as line-based buffering is only really enabled when the $build_command is writing to a tty. Possible options to investigate include:
- the use of `stdbuf` (but that plays poorly with tee)
- the use of `script`, which connects the command to a pseudo-tty but then doesn't allow us to isolate stderr.

**Comment by vkanne-msft** [comment]
How about capturing the entire output into a file buffer (tee) and then grep for STDERR, as it is done today on the middleware, to separate STDOUT and STDERR ?

**Comment by msprotz** [comment]
That doesn't work.

tee uses buffered IO, meaning that you lose the line-based interleaving as soon as you do a redirection through tee

It's not a trivial problem, I spent quite some time researching it yesterday.
