### ISSUE TITLE
Port the branch-to-username feature

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#2]
Description: when the branch name for which we're running CI is one of the known users, send a private message to that user on Slack.

- Read about Bash 4.2 associative arrays https://www.gnu.org/software/bash/manual/bash.html
- Port the feature by including a list at the beginning of the file, then
- change the notification function to erase the channel passed as a parameter and replace it with a private username

**Comment by darrenge** [comment]
From Node-Red, here is the list of authors:

var authors = {
    "ad-l":	"@adl",
    "aseemr" :	"@aseemr",
    "barrybo" :	"@barrybo",
    "beurdouche" : 	"@beurdouche",
    "catalin-hritcu" :	"@catalin",
    "fournet" :	"@fournet",
    "jkzinzindohoue" :	"@jk",
    "karthikbhargavan":	"@karthik",
    "msprotz" :	"@protz" ,
    "mtzguido" :	"@guido",
    "Nikhil Swamy"	: "@nik",
    "parno"	: "@bryan.parno",
    "sishtiaq"	: "@sishtiaq",
    "s-zanella"	: "@santiago",
    "vkanne-msft" : "@vkanne"  
};

**Comment by jk** [comment]
@darrenge I did not contribute. You misspelled the username.

**Comment by darrenge** [comment]
This is just a mapping of Slack names to the emails for the CI build process.

**Comment by msprotz** [comment]
But actually I don't see why we should have the mapping... why not just require people to use their slack identifier, period? And we have a list of known slack members.

**Comment by darrenge** [comment]
good point ... maybe there was an idea to email them as well? Currently, it sends a slack message so maybe Slack ID is enough.

**Comment by vkanne-msft** [comment]
We needed that because people don’t have their Github usernames and slack handles coordinated. Just by taking a github username you cant necessarily send a slack message

**Comment by msprotz** [comment]
Yes, but this doesn't explain why we need to bring the github username into the picture. We could require the branch to directly use the slack username.

Two options:
- p_foo_ → generate a message to `@foo` just like c_bar_ generates a message to `#bar`
- hardcode a list of known slack usernames.

**Comment by vkanne-msft** [comment]
The feature was originally built since devA could submit a fix into c_record and the dev wanted to get original notification. You cannot infer this from the branch name alone.

**Comment by msprotz** [comment]
This issue is about mapping a branch name to a username. Issue #3 is about mapping a branch name to a channel name. I'm not proposing any change for the latter, although there we could make things better.

**Comment by darrenge** [comment]
We have had discussion but no resolution.

Currently is there any naming convention for the branches? Such as username +"_" or anything like that?

Like you say ... we have two options:
1) Generate the slack name ("protz") from the branch name ("origin/protz_newbranch")
2) Use a hard coded list of slack user name and if we find the name in the branch name, then use it. For example, "protznewbranch" would still have protz. However, I think this opens it up to false failures as we would just be looking for a substring that could mean other things.

My vote would be a naming convention of some sort. It is easy to tell people "if you want a private message when the build completes, make sure you have a branch slackname+"_"."

**Comment by msprotz** [comment]
Let's go for the convention `protz_feature_name` with a hardcoded list of slack names in the CI script.

**Comment by msprotz** [comment]
That keeps the existing convention while ruling out false positives.

**Comment by darrenge** [comment]
Based on the Slack team directory (https://everestexpedition.slack.com/team), I get this list. I will get the name from the branch and make sure it is a valid member of the team verified by using this list.
adg 
anitha 
anilam 
adl 
aozgaa 
aseem 
ashay 
barrybo 
bryan.parno
dowling
beurdouche
dowlingbj 
catalin
fournet 
chris.brzuska 
chris.hawblitzel 
wintersteiger 
danelahman 
danfab 
darrenge 
gonthier 
guido 
irinasp
jaylorch 
jk 
karthik
kyod 
konrad.kohbrok 
laure 
leodemoura 
polubelova 
markulf 
mlr-msft 
nadim 
nickbenton
nik 
osavaryb 
wangpeng 
protz
leino 
sishtiaq
santiago
vkanne 
srinath 
taramana 
thomas.sibut-pinote
shaolintl
vdum

**Comment by darrenge** [comment]
Question for @msprotz and @vkanne-msft ... what happens if we have a branch that isn't a c_ and isn't a valid Everest slack team user? Should we still send a slack message to a misc channel of some sort?  I am guessing "no - in that case don't send any slack notification".  This then allows the user running the script to not get a direct message or post to a slack channel if they don't want it (just by naming their branch in a non user name way).

**Comment by msprotz** [comment]
No I don't think we want to lose any notifications. In that case, we should just do nothing and leave the default value for the channel. That way, if someone made a typo or forgot the convention, they can still see the result of their build in the default channel (e.g. #fstar-build or #mitls-build)

**Comment by vkanne-msft** [comment]
Agree with Jonathan. That is how it is setup today as well.

**Comment by darrenge** [comment]
Pull request has been submitted for this feature.

**Comment by msprotz** [comment]
Thanks, will review

**Comment by darrenge** [comment]
All merged and incorporated

**Comment by nik** [comment]
Err, I'm not part of this project ;p

**Comment by vkanne-msft** [comment]
Sorry it seems to have triggered because of some notes that has the @ notation

**Comment by vkanne** [comment]
Ditto - don't think I'm the vkanne you're looking for ;)
