### ISSUE TITLE
Install a windows Python 2.7 into the build machine to proceed with the build

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#25]
This is probably what we want: https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi

**Comment by darrenge** [comment]
Installed Python 2.7.13 in c:\python27.   
Python 3.5 is still on there and is the default python based on that python 3.5 is in the path.

The build process needs python 2.7.13 and should just access it directly or it will be using python 3.5.

If there is a need to remove 3.5 and put 2.7 as the default we can do that.

**Comment by msprotz** [comment]
This seems about right... right now Spartan is hardwired to use c:\python27. We can change the `everest` script to export the right path when launching Spartan, possibly running `easy_install scons`... see #21
