### ISSUE TITLE
Get useful testing for the everest repository

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#33]
Looking at the `ci` script, the `everest-ci` action consists of two parts (https://github.com/project-everest/everest-ci/blob/master/ci#L386)
- build everything from scratch, then
- run `everest test` (via https://github.com/project-everest/everest/blob/master/everest#L611)

This latter `test` function runs various things, which all work, except this: `  mitls-fstar/src/tls/mitls.exe www.google.com 443 -v 1.2 -tlsapi
`

Antoine managed to get it to work on his machine. I don't know why it doesn't work on the build machine. This needs to be fixed so that we have good CI on everest and can notice regressions.

This involves talking to Antoine.

This is VERY HIGH priority and needs to happen as soon as possible.

CC @BarryBo @sishtiaq @darrenge @irinasp @vkanne-msft

**Comment by sishtiaq** [comment]
Try with 
```mitls.exe
 -tlsapi
 -v 1.2 
 -ciphers ECDHE-RSA-CHACHA20-POLY1305-SHA26
 www.google.com 443 ```
This worked for me last time I did it.

**Comment by msprotz** [comment]
```
jonathan@chartreuse:~/Code/mitls-fstar/src/tls (adl_lowlevel_merge) $ ./mitls.exe -v 1.2 -tlsapi -ciphers ECDHE-RSA-CHACHA20-POLY1305-SHA256 www.google.com 443
===============================================
 Starting test TLS 1.3 client...
Fatal error: exception Failure("Not yet implemented:int_cma")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "output/Signature.ml", line 389, characters 10-25
Called from file "output/Handshake.ml", line 988, characters 12-46
Called from file "output/Handshake.ml", line 1103, characters 3-61
Called from file "output/TLS.ml", line 809, characters 16-104
Called from file "output/TLS.ml", line 886, characters 13-26
Called from file "output/TestAPI.ml", line 54, characters 16-33
Called from file "test/mitls.ml", line 107, characters 30-73
```

But thanks for the suggestion :)

**Comment by darrenge** [comment]
Will get on this right away today

**Comment by msprotz** [comment]
This seems to have been fixed starting at https://github.com/project-everest/everest/commit/1f9b98e0
