### ISSUE TITLE
Feature request - add more information to the stderr in the build log, to aid traige of failures

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest-ci#34]
https://raw.githubusercontent.com/project-everest/ci-logs/master/everest-interop-20170111090610.err is an example of an error log, which shows a problem, but not much about what component had the problem.

If the top-level build script wrote a message banner to stderr like:
======
Building miTLS
======
======
Building Kremlin
======

Then any stderr output from that component would be bracketed by headers.  That would make it easier to triage failures back to the right project.

**Comment by msprotz** [comment]
Good point -- the script prints some environment information but it isn't redirected to the log.

**Comment by msprotz** [comment]
Also: https://github.com/project-everest/everest/commit/d27e31bf64e52c6e312eeb8154425232f7f20300
