### ISSUE TITLE
The Docker container that runs VSTS in Linux seems broken

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#35]
We have a docker container (Linux) that exhibits a strange behavior where make in a specific directory fails with a file not found error. However, attaching to the docker container then running make shows that i) the file exists and ii) make succeeds.

No one has a clue; file permissions seem right; perhaps it's due to the fact that the build directory is in a shared folder between Windows and Docker?

**Comment by vkanne-msft** [comment]
Try using VSTS auth tokens to run git commands from our scripts.

**Comment by dzomo** [comment]
New docker container Linux is running on build machine starting 2/28/2017. Let's see if the issue will be seen again.
