### ISSUE TITLE
Add HACL* verification CI 

### ISSUE THREAD

**Issue by vkanne-msft** [project-everest/everest-ci#36]
HACL* CI. 

The repo can move significantly in the recent future and we can work on it after that.

**Comment by msprotz** [comment]
This needs to happen now... taking this.

**Comment by msprotz** [comment]
build definition is in place, first test running

**Comment by msprotz** [comment]
succesfully configured everything, verification is running, any further error to be fixed by @jkzinzindohoue , this is done

**Comment by darrenge** [comment]
I see HACL* is part of miTLS repo ... should it be grouped with miTLS on the dashboard and build definitions or should it be considered separate?

**Comment by msprotz** [comment]
I think we can consider it as separate. Thanks!
