### ISSUE TITLE
Remove the comma in the committer name ("Dzomo, the Everest Yak")

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#37]
This causes conflicts with the email gateway for email notifications and is causing Catalin some trouble.

Task description:
- to be performed in the Linux and Windows environments
- edit the ~/.gitconfig file
- change the `name` key in the `[user]` section to just remove the comma
- in case of trouble, this is the documentation for git config https://git-scm.com/docs/git-config

CC @catalin-hritcu

**Comment by darrenge** [comment]
I went in and fixed this. I see for new docker container has it fixed already and I updated the existing agents (FStar and FStar2).  I also updated the Windows .gitconfig as well.

**Comment by catalin-hritcu** [comment]
@darrenge  Seems to work, many thanks.
