### ISSUE TITLE
Decommission the existing middleware (Node-Red) -to-slack feature

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#4]
Possibly notifying Sreekanth privately instead of decommissionning it entirely

**Comment by msprotz** [comment]
Remove `STDERR : `

**Comment by vkanne-msft** [comment]
P1, since we are getting duplicate notifications

**Comment by msprotz** [comment]
Trap on error in the ci script and send a last-minute notification, e.g. something failed _in_ the script

**Comment by msprotz** [comment]
(This is issue #1)

**Comment by vkanne-msft** [comment]
I thought this was one was just to disable notifications from middleware

**Comment by msprotz** [comment]
Yes, I was just trying to say that decommissionning the middleware requires trap-on-error to be implemented, and that this specific feature is tracked by #1

**Comment by vkanne-msft** [comment]
gotcha

**Comment by vkanne-msft** [comment]
All you got to do for this is to remove the wiring to the slack channel node

**Comment by darrenge** [comment]
Yep - that is the plan. On my to do list.

**Comment by darrenge** [comment]
Removed at the start of the slack channel node chain. It is the one between "Capture STDERR" and "Create Slack Notification".   It is deployed.  I believe that is it but won't close it until test it and make sure not getting any of these messages.

**Comment by darrenge** [comment]
Looks like it is working properly as fstar build only produced the one slack notification... and updated the node-red.script file in VSTS as well.
