### ISSUE TITLE
Enable "everest test" on the ubuntu-from-scratch scenario

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#40]
Now that this is working on Windows, it ought to work on Linux as well.

**Comment by darrenge** [comment]
Who should this be assigned to?

**Comment by msprotz** [comment]
Tahina will take care of enabling test as part of the docker image nightly regeneration.

**Comment by tahina-pro** [comment]
Done. `docker_from_scratch` now successfully builds `projecteverest/everest`, with everything tested and verified, and pushes it to Docker Hub.
