### ISSUE TITLE
Feature request:  don't rebuild branches daily, if there are no changes since last build

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest-ci#41]
I get 3 Slack notifications for the "barrybo" branch daily.  I am not doing active development on the branch, so it would be more efficient if the build system recognized that and skipped the build.

I don't feel I should delete my branch when I'm not working on a project, only to recreate it later when I do.

**Comment by vkanne-msft** [comment]
I am surprised who is even building it. I don’t think the CI is building it unless there is active development.

@darrenge, can you kindly check how the builds are getting triggered ?

**Comment by msprotz** [comment]
Is this #39? I also noticed this.

It's about replacing `*` with `master` somewhere in VSTS.

**Comment by vkanne-msft** [comment]
Yup. It is in the Everest-Nightly-Upgrade-Windows. This is the one causing the nightly builds on all branches. Fixing it.

**Comment by vkanne-msft** [comment]
I believe I fixed this. Changed the build definition of Everest-Nightly-Upgrade
