### ISSUE TITLE
Need to have a good way to run ci scripts on Build Machine (Windows) without using build definitions

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#44]
Currently, to run ci on Windows, people pushing to git and then running the build definition. There are environment issues when trying to run ci script directly on build machine (under windows). We need to figure out what those environment issues are.

**Comment by vkanne-msft** [comment]
Can you capture the errors that you are seeing ?

**Comment by darrenge** [comment]
Got it working ... was in wrong working directory.

* From Cygwin terminal
* Go here:  /cygdrive/c/build/Agent/_work/30/s/FStar  <== check what proper directory for that "30"
* run this:  /home/everbld/everest-ci/ci fstar-ci

Worked just fine
