### ISSUE TITLE
Figure out why we lose this export CI_LOGS=/home/vsts/ci-logs/ setting in linux agent

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#45]
We continually lose this setting: export CI_LOGS=/home/vsts/ci-logs/ in the agent. 

We need to look into why this is happening etc.

**Comment by msprotz** [comment]
Is it not in the ~/.profile or the ~/.bashrc?

If this is the linux agent, I've seen some emails mention `docker run -it bash` -- this should probably be `docker run -it bash --login` to make sure these files are read.

**Comment by darrenge** [comment]
moved to .bashrc and we haven't had a problem with it
