### ISSUE TITLE
Create a new mitls-nightly job

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#49]
Description.

We currently have a VSTS build definition that is run for every commit of mitls. It performs verification.

We need a new VSTS build definition that is run nightly; it is the same as mitls-ci, except:
- it should call "path/to/ci mitls-nightly" instead of "path/to/ci mitls-ci" (where "path/to" is placeholder, I don't actually know the exact value)
- it should be run now, on the Windows container.

I haven't had an opportunity to test mitls hint regeneration; please notify me here as soon as the first build is kicked.

@vkanne-msft can you please assign appropriately?

Thanks,

Jonathan

**Comment by darrenge** [comment]
This was filed as issue #30 already, but since this has more info in it, will close out that one.

**Comment by darrenge** [comment]
@protz updated the ci script and I created the build definition and added to Dashboard. The process is all in place and running.

**Comment by msprotz** [comment]
Except there's a bug that prevents the hints from being generated. But yes, everything else is in place.
