### ISSUE TITLE
Move the fstar-nightly build definition to Windows

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#50]
The F* nightly build is important to regenerate hints and the OCaml snapshot. It hasn't run in a long while, and we have no visibility on when the Linux container will be ready.

Can you please repurpose the FStar nightly build definition to run on Windows? This is a stopgap measure while we wait for the Linux container.

@vkanne-msft can you assign accordingly?

Thanks,

Jonathan

**Comment by darrenge** [comment]
This passed on Nightly Builds. When Linux Build is up and running will disable this build.
