### ISSUE TITLE
Dashboard to report timing stats of individual jobs

### ISSUE THREAD

**Issue by nikswamy** [project-everest/everest-ci#56]
Is there any chance we could get a detailed breakup of the time taken on each make target invoked in utest/ulong?

**Comment by darrenge** [comment]
I believe this is implemented. @irinasp can you confirm?

**Comment by irinasp** [comment]
Timing stats are reported. From robgruen on Slack:
I just pushed this change.  If there are verification times available they'll show on the details page.

**Comment by nikswamy** [comment]
This is great! Thanks : )
