### ISSUE TITLE
change repository connection in the build defintion

### ISSUE THREAD

**Issue by irinasp** [project-everest/everest-ci#58]
vkanne-vsts repository connection is used in almost all Build Definitions in VSTS.
It should be replaced with the connection using everbld account.
Example to see the connection - https://msresearch-ext.visualstudio.com/Everest/Everest%20Team/_build/definitionEditor?definitionId=22&_a=repositories

**Comment by dzomo** [comment]
vkanne-vsts repository connection is replaced with everbld-vsts connection in bld definitions.
