### ISSUE TITLE
vale should not depend on a checked-in kremlin binary

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#62]
but rather, use the one found in PATH. 

For Vale's own CI, we could use the last known good Kremlin version from everest.

```
rm hashes.sh || true
wget https://raw.githubusercontent.com/project-everest/everest/master/hashes.sh
source hashes.sh
if ! [ -d kremlin ]; then
  git clone https://github.com/FStarLang/kremlin
fi
(cd kremlin && git fetch && git reset --hard ${hashes[kremlin]})
make -C kremlin
export PATH=$(pwd)/kremlin:$PATH
export KREMLIN_HOME=$(pwd)/kremlin
```

**Comment by darrenge** [comment]
I can put the above code in the ci script (under vale).  Is there anything else that needs to be done? We need to run a make or anything like that?

**Comment by msprotz** [comment]
I think it could go right here: https://github.com/project-everest/everest-ci/blob/master/ci#L535

And then one could call scons as usual.

Scons is already parameterized to take into account KREMLIN_HOME when it's defined in the environment (I've updated the sketch above), so things should be good. Perhaps check with @BarryBo that he's happy with the new setup and that he's happy about dropping the checked-in binaries? There may be a reason to keep them under version control, I don't know.

Thanks,

Jonathan

**Comment by darrenge** [comment]
Updated and merged
