### ISSUE TITLE
Update the docs on the build process

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#65]
We will want to update docs on the build process.  Mostly internal docs but we will also want to update any external docs that are relevant.
- [x] build environment (slack, vsts, build machine)
- [x] ci script / setup issues and trouble shooting
- [x] docker specific docs
- [x] dashboard specific docs including Node Red
- [x] Design note to set policy for all cross platform dependencies. 
- [x] document on everest homepage how to request access to VisualStudio.com. For both MSFT people and outside people

**Comment by BarryBo** [comment]
Could you also document, on the everest github homepage, how to request access to visualstudio.com, in case someone submits a pull request that fails.  Christoph Wintersteiger, hit this overnight.

**Comment by darrenge** [comment]
This is finished enough to close out this issue. I am sure there will be more additions but there always will be.
