### ISSUE TITLE
STDERR: ../bin/fstar-any.sh: line 11: file: command not found

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#77]
There's a lot of these in the build logs, the container should contain the file utility (apt-get install coreutils perhaps?)

**Comment by irinasp** [comment]
There are still a lot of "command not found" errors in the build logs after adding apt-get install coreutils to Linux container. I am investigating the issue...

**Comment by irinasp** [comment]
The fix is to add file package to the container - apt-get install file. File package is added. The issue will be closed as soon as dockerfile is updated

**Comment by irinasp** [comment]
Pull request for adding file package to dockerfile is submitted. The issue is resolved.
