### ISSUE TITLE
We have no way to start the linux agents automatically after a reboot

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#79]
It looks like windows agents start nice and the linux container is set to start on reboot, but the Docker Service might not be configured properly. The machine rebooted and Tahina said the Docker Service was not started. There is a setting to "Start Docker when you log in" but we want it to be started when machine is rebooted without someone logging in.

**Comment by irinasp** [comment]
Modified registry to fix this issue:
- Launch regedit
- In the registry editor go to HKEY_LOCAL_MACHINE>SOFTWARE>Microsoft>Windows NT>CurrentVersion>Winlogon
- On the right pane of the registry editor there are list of names and it’s values. Among these name check whether AutoAdminLogon, DefaultPassword, DefaultDomain and DefaultUsername are there.
- If any of names are not listed make them by: right click on empty area in the right pane, then select New>String Value and enter the value names: AutoAdminLogon, DefaultPassword, DefaultDomain and DefaultUsername
- After creating them double-click each value and enter the following value data for the particular value 
AutoAdminLogon Value : 1
DefaultDomain Value: Redmond
DefaultUsername Value : the username of the account you want to log in to (everbld)
DefaultPassword Value : the password of the user profile (<everbldPassword>)
- Reboot machine

regedit is updated on the build machine. I am waiting for the time when no runs are going and will reboot build machine

**Comment by irinasp** [comment]
Modified registry didn't help. Corporate policy is enforced on reboot and AutoAdminLogon Value is changed back to 0.
Planning to apply following workaround:
This disables the Exchange ActiveSync (EAS) security policies - a.k.a. the "Enforce these policies prompt" you see 
•	Login with a local admin account
•	Delete any domain accounts on the system which trigger the EAS policies
•	In Regedit delete: 
•	HKLM\SYSTEM\CurrentControlSet\Control\EAS
•	You can use this command:
reg.exe delete "HKLM\SYSTEM\CurrentControlSet\Control\EAS"
•	In Regedit add
•	Under HKLM\Software\Microsoft\ActiveSync, add a DWORD value for “AutoConfigureAADAllowed” with a value of “0”  zero.
•	You can use this command:
reg.exe add "HKLM\Software\Microsoft\activesync" /v AutoConfigureAADAllowed /t REG_DWORD /d 0 /f
•	Add the domain account back if you want
•	Afterwards, you can enable Autologon using the Sysinternals utility or manually editing registry settings.

**Comment by irinasp** [comment]
There is discussion on docker forum about this issue: https://forums.docker.com/t/run-docker-as-a-service/28124. It seems that this scenario is not supported for docker on windows. 
I am going to try to configure hyperV vm for automatic startup http://www.techrepublic.com/blog/data-center/configure-a-hyper-v-vm-for-automatic-startup/ but if this will not work the issue will be closed as won't fix.

**Comment by msprotz** [comment]
This is on hold for the moment until a new version of Docker for windows comes up that supports this scenario

**Comment by gugavaro** [comment]
not relevant anymore since now linux builds run on a linux machine.
