### ISSUE TITLE
VSTS issue: do not run testsuite for the same commit twice

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest-ci#8]
This is silly:

dzomo BOT [10:05 AM]  
Commit 60b42db0 (origin/c_record_aead) is a ﻿⁠⁠⁠success :smiley_cat:﻿⁠⁠⁠
     ﻿⁠⁠⁠Duration:﻿⁠⁠⁠ 18m05s
     ﻿⁠⁠⁠Author:﻿⁠⁠⁠ Nikhil Swamy
     ﻿⁠⁠⁠Message:﻿⁠⁠⁠ disabling a flaky proof in UF1CMA until further notice
     ﻿⁠⁠⁠Project:﻿⁠⁠⁠ FStar
     ﻿⁠⁠⁠Command:﻿⁠⁠⁠ make -C src utest -j 24
     ﻿⁠⁠⁠OS:﻿⁠⁠⁠ CYGWIN_NT-10.0
     ﻿⁠⁠⁠Logs:﻿⁠⁠⁠ stderr stdout

dzomo BOT [10:25 AM]  
Commit 60b42db0 (origin/master) is a ﻿⁠⁠⁠success :smiley_cat:﻿⁠⁠⁠
     ﻿⁠⁠⁠Duration:﻿⁠⁠⁠ 17m43s
     ﻿⁠⁠⁠Author:﻿⁠⁠⁠ Nikhil Swamy
     ﻿⁠⁠⁠Message:﻿⁠⁠⁠ disabling a flaky proof in UF1CMA until further notice
     ﻿⁠⁠⁠Project:﻿⁠⁠⁠ FStar
     ﻿⁠⁠⁠Command:﻿⁠⁠⁠ make -C src utest -j 24
     ﻿⁠⁠⁠OS:﻿⁠⁠⁠ CYGWIN_NT-10.0
     ﻿⁠⁠⁠Logs:﻿⁠⁠⁠ stderr stdout

**Comment by darrenge** [comment]
I am not seeing this any more.  Close it out?

**Comment by msprotz** [comment]
![image](https://cloud.githubusercontent.com/assets/10673049/21802292/65c9fc4e-d725-11e6-889d-36d819315fe0.png)

![image](https://cloud.githubusercontent.com/assets/10673049/21802298/70e1da48-d725-11e6-9237-73eb09ddff1b.png)

Happened again just yesterday.

**Comment by darrenge** [comment]
Oh ... I see the problem. This duplicate message happens when the CI build is ran manually on the build machine. We sometimes want to test out something so we run the CI VSTS job which goes back and gets the info from the last commit for the notification. In the future, if we need to run the VSTS job manually, we should follow up the notification with a note saying it was manually ran.

**Comment by msprotz** [comment]
This also happens when the build is run on a branch, then merged as a fast forward -- another build happens even though the commit hash is the same

**Comment by darrenge** [comment]
From Microsoft VSTS support guys:
"Currently we filter off of the REF specified in the CI trigger settings.  So if you build refs/heads/feature/foo and then merge to refs/heads/master you could get two builds. One for refs/heads/feature/foo and one for refs/heads/master."

**Comment by msprotz** [comment]
Ok. Do they intend to improve this?

**Comment by darrenge** [comment]
I will ask, but my bet is that they won't be changing it.

**Comment by darrenge** [comment]
Confirmed from the PM of VSTS ... there currently aren't plans to add the extra smarts to not fire a second CI if the commit hash doesn't change. He said he will add it to the backlog so they can at least have it recorded though for future features.

Closing this issue.
