### ISSUE TITLE
Fix the logging of test runs so properly describing log

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#82]
mitl-nightly has logs labeled mitls-ci

hacl star nightly has logs labeled hacl-ci

**Comment by darrenge** [comment]
Looking at this some more ... if we change this, we lose all the historical aspect from the dashboard. The file name isn't that critical anyways as no one would realistically go look at CI-LOGS repo. The main thing is that the dashboard goes to the proper file and shows the proper logs.

**Comment by msprotz** [comment]
There is a risk of collision when the nightly and the ci run try to write to the same log file, I think. Using distinct "stems" guarantees that if two runs happen at the same time on the same commit, they'll still touch different filenames.

**Comment by darrenge** [comment]
Hmmm .. guess we should fix them then.

**Comment by msprotz** [comment]
ok I double-checked and they have the VSTS build number in them already, so this should be enough to disambiguate, right? we do know that VSTS won't assign the same build number twice?

**Comment by darrenge** [comment]
Right ... build number should just be incremental.  Build number will make it unique enough.

**Comment by darrenge** [comment]
i think we just keep it the way it is which will keep the history etc. Once again ... closing this out.
