### ISSUE TITLE
Add a "YES_CI" in the commit message to opt in for a CI

### ISSUE THREAD

**Issue by darrenge** [project-everest/everest-ci#84]
Request from @jkzinzindohoue 

They want Hacl* CI to run on "master" and "dev" branches only. Sometimes, there might be a need to run a CI on a different branch. Having a "YES_CI" in the commit message could be a trigger to opt-in for the CI. Normally, people can just launch a build using VSTS on their specific branch but interns etc might not have access to VSTS.

**Comment by jkzinzindohoue** [comment]
@msprotz  is it closed because implemented or because it will not happen ?
