### ISSUE TITLE
Stats for individual queries using `--hint_info` output

### ISSUE THREAD

**Issue by s-zanella** [project-everest/everest-ci#88]
(Stemming from discussion in https://github.com/mitls/hacl-star/issues/13.)

It would be very useful for the dashboard to report statistics about individual queries, in addition to overall per-module verification times (https://github.com/project-everest/everest-ci/issues/56).

This requires passing `--hint_info` to F*, which generates much longer logs. If this is too much,  we could restrict the more detailed stats to nightly builds.

**Comment by msprotz** [comment]
https://github.com/project-everest/everest-ci/blob/master/ci#L493 from this line, it seems like this is already happening for nightlies

**Comment by s-zanella** [comment]
Great, then no reason no to have detailed stats.

**Comment by msprotz** [comment]
However, it seems like OTHERFLAGS is not passed properly to sub-commands in nightlies...

**Comment by msprotz** [comment]
Scrap that, OTHERFLAGS is working, I just got confused.... closing.
