### ISSUE TITLE
Linux agent lost communication

### ISSUE THREAD

**Issue by irinasp** [project-everest/everest-ci#89]
This is not consistent issue.
Repro:
1. Start the run using build definition from VSTS, example FStar-BinaryBuild-Linux-Build 6986
Result:
The run is failing after 45 minutes of running with following error:
The agent Everest-CI-3 lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

**Comment by s-zanella** [comment]
Saw this a couple of times. Seems to happen randomly.

**Comment by irinasp** [comment]
The log file is available from Docker right click menu Settings\Diagnose & Feedback\log file.
I could see the error in the log file:
[03:25:16.985][VpnKit         ][Error  ] com.docker.slirp.exe: PPP.listen callback caught Ipv4.Make(Ethif)(Arpv4).Routing.No_route_to_destination_address(_)
Searching in the Docker forum I found that people complaining about this problem and the workaround is to reset docker to factory defaults: https://forums.docker.com/t/com-docker-slirp-is-using-my-containers-ports/16663/2 
I will reset docker this afternoon when no runs are queued\ in progress and see if it will help with this issue.

**Comment by irinasp** [comment]
Reset docker to factory defaults doesn't help.
I noticed that there are newer version of Ubuntu 16.04-x64 for VSTS. Updating the agent version on Linux container on build machine.

**Comment by irinasp** [comment]
After Linux agent version update there is no repro for this problem. I am going to watch the runs for one more day and close this issue if runs will be finishing successfully.

**Comment by darrenge** [comment]
I haven't seen an issue with this at all for the past week or so ... I think we can close this out.

**Comment by irinasp** [comment]
It seems that Linux agent version update fixed the issue. There are no connection issues.
