### ISSUE TITLE
Trigger a new snapshot commit through CI

### ISSUE THREAD

**Issue by kyoDralliam** [project-everest/everest-ci#95]
It happens sometimes that I develop on a machine which does not have the ocaml version of reference for the snapshot of F*. In these case I prefer not pushing the fresh snapshot in order  to minimize the commit size (and anyway  a fresh snapshot will be commited in the 24h if it is on master). Nonetheless, it would be nice to have a trigger like `***SNAP**` to ask the CI to commit a fresh ocaml snapshot in case of build success.

**Comment by wintersteiger** [comment]
+1 I'd also like a custom trigger (to use a newer Z3 than the reference). I looked around for a little bit, but I couldn't find anything about that in the VSTS docs. Do you know whether that's possible at all?

**Comment by msprotz** [comment]
You can trigger a nightly build which will, I believe, do precisely that (regenerate hints + snapshots). You have to trigger it via the VSTS web interface though (I have an upcoming issue for VSTS-related pain).
